version: '3'

services:
  bt_py_sim:
    build:
      context: .
      dockerfile: docker/Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    # command: ["python", "main.py", "--simulation"]
    stdin_open: true
    tty: true
